version: '3'
services:
  server:
    container_name: server
    restart: always
    build: .
    volumes: 
      - '.:/usr/src/server'
      - './usr/src/server/node_modules'
    ports:
      - '5005:5000'
    links:
      - client

  client:
    container_name: client
    restart: always
    build: ./client
    volumes: 
      - '.:/usr/src/server/client'
      - './usr/src/server/client/node_modules'
    ports:
      - '3003:3000'

