version: '3.7'
services:
  server:
    container_name: server
    build: .
    restart: always
    ports:
      - '5000:5000'
    links:
      - client

  client:
    container_name: client
    restart: always
    build: ./client
    volumes:
      - '.:/client'
      - '/client/node_modules'
    ports:
      - '3003:3000'
    environment:
      - NODE_ENV=development
    tty: true
    

