version: '3'
services:
  server:
    container_name: server
    restart: always
    build: .
    ports:
      - '5000:5000'
    links:
      - client

  client:
    container_name: client
    restart: always
    build: ./client
    ports:
      - '3000:3000'
