version: '3.7'
services:
  server:
    container_name: server
    build: .
    ports:
      - '5000:5000'
    links:
      - client

  client:
    container_name: client
    build: ./client
    ports:
      - '3003:3000'

